#
server:
  port: 9000
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-springboot-security-jwt
####################
#
####################
jwt:
  secret: secret
  expiration: 7200000
  token: Authorization